/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/17/2013
 */

package com.lodogame.ldsg.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.game.utils.IDGenerator;
import com.lodogame.ldsg.service.HeroService;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class HeroServiceImplTest extends AbstractTestNGSpringContextTests {

	String userId = "49ff94dbe9ac4b3f953a1870718cb32b";

	@Autowired
	private HeroService heroService;

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.HeroServiceImpl#getUserHeroBO(String)
	 */
	@Test
	public void getUserHeroBO() {

		// List<BattleHeroBO> list =
		// this.heroService.getUserBattleHeroBOList("b661c63b7dbc433d8622bcba35838a6a");
		//
		// for (BattleHeroBO bo : list) {
		// System.out.println(bo.getLife());
		// }
		heroService.addUserHero(userId, IDGenerator.getID(), 1, 0, 0);

	}
}
