/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : chenjian
 * Created : 07/05/2013
 */

package com.lodogame.ldsg.service.impl;

import static org.testng.Assert.assertNotNull;


import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.ldsg.bo.PowerRankBO;
import com.lodogame.ldsg.service.RankService;
import org.testng.annotations.*;
import static org.testng.Assert.*;
import com.lodogame.ldsg.service.impl.RankServiceImpl;
import com.lodogame.ldsg.bo.WealthRankBO;
import com.lodogame.ldsg.bo.ForcesRankBO;
import com.lodogame.ldsg.bo.AttackRankBO;
import com.lodogame.ldsg.bo.DefenceRankBO;
import com.lodogame.ldsg.bo.HpRankBO;


@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class RankServiceImplTest extends AbstractTestNGSpringContextTests{

	@Autowired
	private RankService rankService;

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getPowerRanks()
	 */
	@Test
	public void getPowerRanks() {
		List<PowerRankBO> powerranks = rankService.getPowerRanks();
		assertNotNull(powerranks, "powerranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getWealthRanks()
	 */
	@Test
	public void getWealthRanks() {
		List<WealthRankBO> wealthranks = rankService.getWealthRanks();
		assertNotNull(wealthranks, "wealthranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getForcesRanks()
	 */
	@Test
	public void getForcesRanks() {
		List<ForcesRankBO> forcesranks = rankService.getForcesRanks();
		assertNotNull(forcesranks, "forcesranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getAttackRanks()
	 */
	@Test
	public void getAttackRanks() {
		List<AttackRankBO> attackranks = rankService.getAttackRanks();
		assertNotNull(attackranks, "attackranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getDefenceRanks()
	 */
	@Test
	public void getDefenceRanks() {
		List<DefenceRankBO> defenceranks = rankService.getDefenceRanks();
		assertNotNull(defenceranks, "defenceranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getHpRanks()
	 */
	@Test
	public void getHpRanks() {
		List<HpRankBO> hpranks = rankService.getHpRanks();
		assertNotNull(hpranks, "hpranks cannot be null");
	}

	/**
	 *
	 * @see com.lodogame.ldsg.service.impl.RankServiceImpl#getRankStatTime()
	 */
	@Test
	public void getRankStatTime() {
		long rankstattime = rankService.getRankStatTime();
		assertNotNull(rankstattime, "rankstattime cannot be null");
	}

	
}
