/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/21/2013
 */

package com.lodogame.ldsg.service.impl;

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.Test;

import com.lodogame.ldsg.service.WebApiService;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class WebApiServiceImplTest extends AbstractTestNGSpringContextTests {

	String partnerId = "1001";
	String serverId = "s1";
	String partnerUserId = "es.23107841";
	BigDecimal amount = new BigDecimal(0.1);

	@Autowired
	private WebApiService webApiService;

	/**
	 * 
	 * @see com.lodogame.ldsg.service.impl.WebApiServiceImpl#createOrder(String,String,String,Double)
	 */
	@Test
	public void createOrder() {

		//String payurl = webApiService.createOrder(partnerId, serverId, partnerUserId, amount);
		//System.out.println(payurl);
	}
}
