/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 07/15/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.*;
import static org.testng.Assert.*;

import com.lodogame.game.dao.ActiveCodeDao;
import com.lodogame.game.dao.impl.mysql.ActiveCodeDaoMysqlImpl;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class ActiveCodeDaoImplTest extends AbstractTestNGSpringContextTests {

	@Autowired
	ActiveCodeDao activeCodeDao;

	@BeforeClass
	public void setUpBeforeClass() {
		// TODO add setup code.
	}

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.ActiveCodeDaoMysqlImpl#active(String,String)
	 */
	@Test
	public void active() {
		activeCodeDao.active("4444", "111111", "1001");
	}

}
