/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : jacky
 * Created : 05/24/2013
 */

package com.lodogame.game.dao.impl.mysql;

import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.*;
import static org.testng.Assert.*;
import com.lodogame.game.dao.impl.mysql.SystemGoldSetDaoMysqlImpl;
import java.util.List;
import com.lodogame.model.SystemGoldSet;

@ContextConfiguration(locations = { "classpath:applicationContext-test.xml" })
public class SystemGoldSetDaoMysqlImplTest {

	/**
	 * 
	 * @see com.lodogame.game.dao.impl.mysql.SystemGoldSetDaoMysqlImpl#getList(int)
	 */
	@Test
	public void getList() {

	}

}
